Add missing dependency @types/hoist-non-react-statics, closes #3837
jaredpalmer/formik pull request #3860
Opened 2023-08-06 19:27 UTC by patik

This package is needed by Formik but it was not included in the dependency list.

2023-08-31 20:34 UTC, probablyup approved these changes
Thank you

2023-08-31 20:37 UTC, probablyup commented
Could you add a changeset please?

2023-09-08 13:56 UTC, probablyup approved these changes
Thanks!

2023-09-08 13:57 UTC, probablyup requested changes
Actually sorry, I think this type needs to go in formik's specific package.json not the top one?

2023-09-10 17:12 UTC, patik commented
> Actually sorry, I think this type needs to go in formik's specific package.json not the top one?

Do you mean `packages/formik/package.json`? This dependency is already listed in that package (it's been there for at least 4 years), but the issue seems to persist unless the dependency is in the root-level package.json.

2023-09-11 14:04 UTC, probablyup commented
> > Actually sorry, I think this type needs to go in formik's specific package.json not the top one?
> 
> Do you mean `packages/formik/package.json`? This dependency is already listed in that package (it's been there for at least 4 years), but the issue seems to persist unless the dependency is in the root-level package.json.

You're seeing that a dependency in a workspace package isn't installing downstream in your client package because it's not present in the workspace root package.json? That seems unlikely.

2023-09-17 19:38 UTC, patik commented
> It's currently in `devDependencies`, perhaps move it to `dependencies` in that file?

Indeed, that change resolves the issue. I made the change, and now if I install Formik in another project, the `@types/hoist-non-react-statics` package is also installed, and the TS error goes away.

2023-09-17 19:39 UTC, probablyup commented on package.json
> +    "@types/hoist-non-react-statics": "^3.3.1",
Thanks, this one can be removed now

2023-09-17 19:41 UTC, patik commented on package.json
> +    "@types/hoist-non-react-statics": "^3.3.1",
Yep, fixed.

2023-09-17 19:42 UTC, probablyup approved these changes
Awesome, thank you :)

2023-09-17 19:48 UTC, probablyup commented
Pinged Jared to fix the required check settings, please hold

2023-09-17 19:49 UTC, merged